# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

source=$HOME/.config/hypr/configs/general.conf
source=$HOME/.config/hypr/configs/keybinds.conf
source=$HOME/.config/hypr/configs/autostart.conf
source=$HOME/.config/hypr/configs/window-rules.conf
