lastupdatecheck: 1697297796
recentrepos:
- /home/emmanuel/.dotfiles
- /home/emmanuel/ghq/github.com/govahq/monorepo
- /home/emmanuel/ghq/github.com/Armadillidiid/starter-kit
- /home/emmanuel/ghq/github.com/govahq/dashboardDesign
- /home/emmanuel/ghq/github.com/Armadillidiid/reddit-clone
- /home/emmanuel/ghq/github.com/govahq/payout
- /home/emmanuel/ghq/github.com/govahq/USSDLandingPage
- /home/emmanuel/ghq/github.com/t3-oss/t3-env
- /home/emmanuel/Documents/tanstack-table-demo
- /home/emmanuel/ghq/github.com/govahq/GovaAdminBackOffice
- /home/emmanuel/Documents/leetcode
- /home/emmanuel/ghq/github.com/Armadillidiid/documentation
- /home/emmanuel/Documents/hms
- /home/emmanuel/ghq/github.com/ThePrimeagen/kata-machine
- /home/emmanuel/ghq/github.com/docker/getting-started-app
- /home/emmanuel/ghq/github.com/Armadillidiid/portfolio
- /home/emmanuel/ghq/github.com/Armadillidiid/food-delivery-ecommerce
- /home/emmanuel/ghq/github.com/Armadillidiid/react-game-store
startuppopupversion: 5
customcommandshistory:
- 'refactor: Move Dashboard array mappings into separate files'
hidecommandlog: false
ignorewhitespaceindiffview: false
