windowrule = workspace special:monitor silent, match:class (kitty)$, match:title (btop)$
windowrule = workspace special:minimized silent, match:class ^(Spotify)$
windowrule = workspace special:discord, match:class ^(vesktop)$
windowrule = workspace special:whatsapp, match:class (com.rtosta.zapzap)
windowrule = workspace special:ai, match:title (Open WebUI)
windowrule = workspace special:ai, match:title (Claude)
windowrule = workspace special:ai, match:title (ChatGPT)
windowrule = workspace special:cliq, match:class (org.gnome.clocks)
windowrule = workspace special:generic-2, match:class (Code)
windowrule = workspace 5, match:class (ticktick)

# Float
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float on, match:class (xdg-desktop-portal-gtk)
windowrule = float on, match:class ^([Rr]ofi)$

windowrule = group deny, size 489 275, float on, pin on, keep_aspect_ratio on, move ((monitor_w*1)-window_w-10) ((monitor_h*1)-window_h-10), match:class (firefox), match:title (Picture-in-Picture)


windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# Windscribe
windowrule = size 327 320, float on, match:class (Windscribe)

# Showmethekey
windowrule = float on, move (670) (800), pin on, border_size 0, no_blur on, force_rgbx on, opacity 0.9, decorate 0, match:class (showmethekey-gtk)
# windowrulev2 = size 580 60, class:(showmethekey-gtk),

# Prevent Davinci Resolve from closing the popup on mouse movement / pointer leave (e.g. "Change Clip Duration")
windowrule = tag +drpopup, match:class ^(resolve)$, match:float 1
windowrule = stay_focused on, match:tag drpopup
